name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Install
        working-directory: coding
        run: poetry install
      - name: Lint
        working-directory: coding
        run: $(poetry env info -p)/bin/poe lint
      - name: Test
        working-directory: coding
        run: $(poetry env info -p)/bin/poe test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coding/coverage.lcov